const instituteData = [
  {
    college: "Indian Institute of Technology Madras",
    university: "Indian Institute of Technology",
    location: "Chennai, Tamil Nadu",
    type: "B.Tech",
    areaStatus: "Urban",
    activeStatus: "Active",
    ranking: 1,
  },
  {
    college: "Indian Institute of Science",
    university: "Autonomous Institute",
    location: "Bengaluru, Karnataka",
    type: "M.Sc",
    areaStatus: "Urban",
    activeStatus: "Active",
    ranking: 2,
  },
  {
    college: "Delhi Technological University",
    university: "Delhi State University",
    location: "New Delhi, Delhi",
    type: "B.Tech",
    areaStatus: "Urban",
    activeStatus: "Active",
    ranking: 10,
  },
  {
    college: "Netaji Subhas University of Technology",
    university: "Delhi State University",
    location: "New Delhi, Delhi",
    type: "B.Tech",
    areaStatus: "Urban",
    activeStatus: "Active",
    ranking: 12,
  },
  {
    college: "Jadavpur University Engineering College",
    university: "Jadavpur University",
    location: "Kolkata, West Bengal",
    type: "B.Tech",
    areaStatus: "Urban",
    activeStatus: "Active",
    ranking: 8,
  },
  {
    college: "Vellore Institute of Technology",
    university: "Deemed University",
    location: "Vellore, Tamil Nadu",
    type: "B.Tech",
    areaStatus: "Urban",
    activeStatus: "Active",
    ranking: 6,
  },
  {
    college: "SRM Engineering College",
    university: "SRM Institute of Science and Technology",
    location: "Kattankulathur, Tamil Nadu",
    type: "B.Tech",
    areaStatus: "Urban",
    activeStatus: "Active",
    ranking: 9,
  },
  {
    college: "Birla Institute of Technology",
    university: "BIT Mesra",
    location: "Ranchi, Jharkhand",
    type: "B.Tech",
    areaStatus: "Rural",
    activeStatus: "Active",
    ranking: 18,
  },
  {
    college: "National Institute of Technology Trichy",
    university: "NIT Council",
    location: "Tiruchirappalli, Tamil Nadu",
    type: "B.Tech",
    areaStatus: "Urban",
    activeStatus: "Active",
    ranking: 7,
  },
  {
    college: "National Institute of Technology Warangal",
    university: "NIT Council",
    location: "Warangal, Telangana",
    type: "B.Tech",
    areaStatus: "Urban",
    activeStatus: "Active",
    ranking: 15,
  },

  {
    college: "Amity School of Engineering",
    university: "Amity University",
    location: "Noida, Uttar Pradesh",
    type: "B.Tech",
    areaStatus: "Urban",
    activeStatus: "Active",
    ranking: 40,
  },
  {
    college: "Lovely Professional University",
    university: "Private University",
    location: "Phagwara, Punjab",
    type: "B.Tech",
    areaStatus: "Rural",
    activeStatus: "Active",
    ranking: 32,
  },
  {
    college: "Shiv Nadar Engineering College",
    university: "Shiv Nadar University",
    location: "Dadri, Uttar Pradesh",
    type: "B.Tech",
    areaStatus: "Rural",
    activeStatus: "Active",
    ranking: 28,
  },
  {
    college: "Ashoka University College of Sciences",
    university: "Ashoka University",
    location: "Sonipat, Haryana",
    type: "B.Sc",
    areaStatus: "Rural",
    activeStatus: "Active",
    ranking: 25,
  },
  {
    college: "Symbiosis Institute of Technology",
    university: "Symbiosis International University",
    location: "Pune, Maharashtra",
    type: "B.Tech",
    areaStatus: "Urban",
    activeStatus: "Active",
    ranking: 22,
  },
  {
    college: "MIT World Peace University",
    university: "MIT-WPU",
    location: "Pune, Maharashtra",
    type: "B.Tech",
    areaStatus: "Urban",
    activeStatus: "Active",
    ranking: 30,
  },
  {
    college: "Kalinga Institute of Industrial Technology",
    university: "KIIT University",
    location: "Bhubaneswar, Odisha",
    type: "B.Tech",
    areaStatus: "Urban",
    activeStatus: "Active",
    ranking: 27,
  },
  {
    college: "SASTRA Deemed University",
    university: "SASTRA University",
    location: "Thanjavur, Tamil Nadu",
    type: "B.Tech",
    areaStatus: "Rural",
    activeStatus: "Active",
    ranking: 19,
  },
  {
    college: "PSG College of Technology",
    university: "Anna University",
    location: "Coimbatore, Tamil Nadu",
    type: "B.Tech",
    areaStatus: "Urban",
    activeStatus: "Active",
    ranking: 14,
  },
  {
    college: "Thiagarajar College of Engineering",
    university: "Anna University",
    location: "Madurai, Tamil Nadu",
    type: "B.Tech",
    areaStatus: "Urban",
    activeStatus: "Active",
    ranking: 20,
  },

  {
    college: "Government Polytechnic College",
    university: "State Board of Technical Education",
    location: "Gulbarga, Karnataka",
    type: "Polytechnic",
    areaStatus: "Urban",
    activeStatus: "Active",
    ranking: 55,
  },
  {
    college: "Rural Polytechnic Institute",
    university: "State Technical Board",
    location: "Chitradurga, Karnataka",
    type: "Polytechnic",
    areaStatus: "Rural",
    activeStatus: "Inactive",
    ranking: 92,
  },
  {
    college: "Government Engineering College",
    university: "Gujarat Technological University",
    location: "Bhavnagar, Gujarat",
    type: "B.Tech",
    areaStatus: "Urban",
    activeStatus: "Active",
    ranking: 48,
  },
  {
    college: "LD College of Engineering",
    university: "Gujarat Technological University",
    location: "Ahmedabad, Gujarat",
    type: "B.Tech",
    areaStatus: "Urban",
    activeStatus: "Active",
    ranking: 26,
  },
  {
    college: "Institute of Chemical Technology",
    university: "Deemed University",
    location: "Mumbai, Maharashtra",
    type: "B.Tech",
    areaStatus: "Urban",
    activeStatus: "Active",
    ranking: 5,
  },
  {
    college: "College of Engineering Trivandrum",
    university: "APJ Abdul Kalam Technological University",
    location: "Thiruvananthapuram, Kerala",
    type: "B.Tech",
    areaStatus: "Urban",
    activeStatus: "Active",
    ranking: 24,
  },
  {
    college: "Model Engineering College",
    university: "APJ Abdul Kalam Technological University",
    location: "Kochi, Kerala",
    type: "B.Tech",
    areaStatus: "Urban",
    activeStatus: "Active",
    ranking: 21,
  },
  {
    college: "Government Engineering College",
    university: "University of Rajasthan",
    location: "Ajmer, Rajasthan",
    type: "B.Tech",
    areaStatus: "Urban",
    activeStatus: "Active",
    ranking: 52,
  },
  {
    college: "Rajasthan Technical Institute",
    university: "Rajasthan Technical University",
    location: "Kota, Rajasthan",
    type: "Polytechnic",
    areaStatus: "Urban",
    activeStatus: "Active",
    ranking: 47,
  },
  {
    college: "Central Institute of Plastics Engineering",
    university: "Central Government Institute",
    location: "Bhopal, Madhya Pradesh",
    type: "Diploma",
    areaStatus: "Urban",
    activeStatus: "Active",
    ranking: 60,
  },

  {
    college: "Government Arts and Science College",
    university: "University of Madras",
    location: "Villupuram, Tamil Nadu",
    type: "B.Sc",
    areaStatus: "Rural",
    activeStatus: "Active",
    ranking: 68,
  },
  {
    college: "St. Xavier's College",
    university: "University of Mumbai",
    location: "Mumbai, Maharashtra",
    type: "B.A",
    areaStatus: "Urban",
    activeStatus: "Active",
    ranking: 4,
  },
  {
    college: "Loyola College",
    university: "University of Madras",
    location: "Chennai, Tamil Nadu",
    type: "B.Sc",
    areaStatus: "Urban",
    activeStatus: "Active",
    ranking: 3,
  },
  {
    college: "Presidency College",
    university: "University of Calcutta",
    location: "Kolkata, West Bengal",
    type: "B.Sc",
    areaStatus: "Urban",
    activeStatus: "Active",
    ranking: 11,
  },
  {
    college: "Rural Degree College",
    university: "State University",
    location: "Sitapur, Uttar Pradesh",
    type: "B.A",
    areaStatus: "Rural",
    activeStatus: "Inactive",
    ranking: 95,
  },
  {
    college: "Government Degree College",
    university: "Himachal Pradesh University",
    location: "Mandi, Himachal Pradesh",
    type: "B.Sc",
    areaStatus: "Rural",
    activeStatus: "Active",
    ranking: 70,
  },
  {
    college: "North Eastern Regional Institute of Science",
    university: "Central University",
    location: "Itanagar, Arunachal Pradesh",
    type: "B.Tech",
    areaStatus: "Rural",
    activeStatus: "Active",
    ranking: 58,
  },
  {
    college: "Tripura Institute of Technology",
    university: "Tripura University",
    location: "Agartala, Tripura",
    type: "B.Tech",
    areaStatus: "Urban",
    activeStatus: "Active",
    ranking: 66,
  },
  {
    college: "Assam Engineering College",
    university: "Gauhati University",
    location: "Guwahati, Assam",
    type: "B.Tech",
    areaStatus: "Urban",
    activeStatus: "Active",
    ranking: 49,
  },
  {
    college: "Nagaland Polytechnic",
    university: "State Technical Board",
    location: "Dimapur, Nagaland",
    type: "Polytechnic",
    areaStatus: "Urban",
    activeStatus: "Inactive",
    ranking: 90,
  }
];
